version: "2.1"
services:
  healthchecks:
    image: lscr.io/linuxserver/healthchecks:latest
    container_name: healthchecks
    environment:
      - PUID=1000
      - PGID=1000
      - SITE_ROOT=<SITE_ROOT>
      - SITE_NAME=<SITE_NAME>
      - DEFAULT_FROM_EMAIL=<DEFAULT_FROM_EMAIL>
      - EMAIL_HOST=<EMAIL_HOST>
      - EMAIL_PORT=<EMAIL_PORT>
      - EMAIL_HOST_USER=<EMAIL_HOST_USER>
      - EMAIL_HOST_PASSWORD=<EMAIL_HOST_PASSWORD>
      - EMAIL_USE_TLS=<True or False>
      - SUPERUSER_EMAIL=<SUPERUSER_EMAIL>
      - SUPERUSER_PASSWORD=<SUPERUSER_PASSWORD>
      - REGENERATE_SETTINGS=True/False #optional
      - SITE_LOGO_URL=<SITE_LOGO_URL> #optional
      - ALLOWED_HOSTS=<ALLOWED_HOSTS> #optional
      - SECRET_KEY=<SECRET_KEY> #optional
      - APPRISE_ENABLED=True/False #optional
    volumes:
      - <path to data on host>:/config
    ports:
      - 8000:8000
    restart: unless-stopped
  cron:
    image: alpine-cron-curl
    container_name: healthchecks_cron
    depends_on:
      - healthchecks
    restart: unless-stopped
    environment:
      - PING_KEY=<HELATHCHECKS_PING_KEY>
      - TZ=<TIMEZONE>
      - SERVER_IP=<POINT_TO_SERVER_IP>
    volumes:
      - <path to cron data on host>:/cron
